```{r}
library(tidyverse)
diamonds <- read_csv("diamonds.csv")
glimpse(diamonds)
View(diamonds)
```

```{r}
#DISPERSION
#1.1
ggplot(diamonds, aes(x= carat, y = price)) + 
  geom_point()
```
```{r}
#1.2
#1.3
ggplot(diamonds, aes(x= carat, y = price, color = clarity)) + 
  geom_point()
```
```{r}
#HISTOGRAMA
#2.1
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins = 40)
```
```{r}
#2.2
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins = 40)+
  scale_x_log10()
```
```{r}
#BOXPLOTS
#3.1

ggplot(diamonds, aes(x = cut, y = price))+
  geom_boxplot()+
  scale_y_log10()
```
```{r}
#3.2
ggplot(diamonds, aes(x = cut, y = price, fill = cut))+
  geom_boxplot()+
  scale_y_log10()
```
```{r}
#FACETING
#4.1
filtered_price <- diamonds %>%
  filter (cut %in% c("Good", "Ideal", "Premium") & price > 1000)
filtered_price
```
```{r}
#4.2 Grafico de barras
ggplot(filtered_price, aes(x=cut, y= depth)) +
  geom_col()
```
```{r}
#4.3
ggplot(filtered_price, aes(x=cut, y= depth)) +
  geom_col()+
   facet_wrap(~ clarity)

```
```{r}
#4.4
ggplot(filtered_price, aes(x=cut, y= depth, fill = clarity)) +
  geom_col()+
   facet_wrap(~ clarity)

```

```{r}
#GROUPING AND SUMMARIZING
#1
median_dimension_diamond <- diamonds %>%
  group_by(cut) %>%
  summarize(mediaX = mean(x), mediaY = mean(y), mediaZ = mean(z))
  
median_dimension_diamond
```
```{r}
#2
cut_premium <- diamonds %>%
  filter(cut=="Premium")%>%
  group_by(clarity)%>%
  summarize(minPrice = min(price), maxPrice = max(price))

cut_premium
```

```{r}
#3
ggplot(cut_premium, aes(x=clarity, y= maxPrice, fill = clarity)) +
  geom_col()
```

